#**Introducción a NumPy** 

La librería NumPy (Numerical Python) proporciona una interfaz para guardar y operar sobre arreglos de datos. Los arreglos en NumPy son como el tipo de datos list disponible en Python, pero proporcionan mucho más operaciones y eficiencia en la manipulación y el manejo de los arreglos conforme estos incrementan de tamaño.




Para importar la libreria 

In [0]:
import numpy as np

In [0]:
np.__version__

'1.17.4'

In [0]:
np?


##**Tipos de Datos en Python**

Python en un lenguaje de tipado dinámico y no requiere que cada variable sea declarada explicitamente a diferencia de otros lenguajes.

In [0]:
result = 0
for i in range(100):
    result += i

In [0]:
result

4950

In [0]:
x=4

In [0]:
x='four'

##**Enteros en Python**



*   La implementacion standard de Python está escrita en C
*   Si definimos un entero en Python, x = 10000, x es un apuntador a una estructura de C







Un entero en Python contiene cuatro partes:

***Ob_refcnt,*** un contador que ayuda en la asignación y liberación de memoria.


***Ob_type***, codifica el tipo de variable.


***Ob_size***, especifica el tamaño.


***Ob_digit***, contiene el valor asignado que representa la variable.

##**Listas en Python**

Una lista es una estructura de datos que permite colectar objetos

*   De enteros 




In [0]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
type(L)

list

In [0]:
type(L[2])

int



*   caracteres de texto



In [0]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [0]:
type(L2[5])

str

In [0]:
type(L2)


list

In [0]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

Esta felixibilidad tiene un costo pues cada elemento en la lista contiene es una referencia a una estructura que define el objeto de Python.


En el caso especial que todas las entradas son del mismo tipo habrá información redundante: Sería mas eficiente usar un arreglo de tipo fijo.

La lista contiene un apuntador a un bloque de apuntadores, cada uno apuntando a un objeto de Python (como el objeto entero que vimos antes)


La lista puede tener objetos y datos de cualquier tipo


El arreglo fijo no puede hacerlo, pero es mas eficiente para guardar y manipular los datos

##**Arreglos de Tipo Fijo en Python**

En Python hay diferentes opciones para guardar datos en buffers de tipo fijo.


El modulo interno array (disponible a partir de Python 3.3) sirve para crear arreglos densos de tipo uniforme:

In [0]:
import array
L=list(range(10))
A=array.array("i",L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Aquí 'i' indica que las entradas son enteros.


El objeto ndarray de la libreria NumPy es mucho mas útil ya que implementa operaciones sobre los datos contenidos.


Antes de explorar estas operaciones, veamos diversas maneras de crear arreglos de NumPy

##**Crear Arreglos a partir de Listas de Python**

In [0]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [0]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [0]:

np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

A diferencia de las listas, los arreglos de NumPy pueden ser explicitamente multi-dimensionales.


A continuación, una forma de inicializar un arreglo multidimensional usando una lista de listas

In [0]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [0]:
np.array([range(i) for i in [2, 4, 6]])

array([range(0, 2), range(0, 4), range(0, 6)], dtype=object)

In [0]:
np.array([range(i + 3) for i in [2, 4, 6]])

array([range(0, 5), range(0, 7), range(0, 9)], dtype=object)

In [0]:
np.array([range(i, i + 4) for i in [2, 4, 6]])

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [0]:
np.array([range(i, i+2 ) for i in [2, 4, 6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [0]:
np.array([range(i, i+2) for i in [2, 5, 2, 3]])

array([[2, 3],
       [5, 6],
       [2, 3],
       [3, 4]])

##**Creando Arreglos**

In [0]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.full((4,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [0]:
np.zeros((10,1), dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [0]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
np.arange(5, 20, 2.1, dtype=float)

array([ 5. ,  7.1,  9.2, 11.3, 13.4, 15.5, 17.6, 19.7])

In [0]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
np.linspace(50, 1000, num=10)

array([  50.        ,  155.55555556,  261.11111111,  366.66666667,
        472.22222222,  577.77777778,  683.33333333,  788.88888889,
        894.44444444, 1000.        ])

In [0]:
np.random.random((3, 3))

array([[0.66262715, 0.15358032, 0.057302  ],
       [0.28477308, 0.3521879 , 0.55492055],
       [0.59303616, 0.09490834, 0.87971085]])

In [0]:
np.random.random((4, 5))

array([[0.42492989, 0.35417044, 0.81967653, 0.29056389, 0.62967609],
       [0.50346737, 0.8391905 , 0.32140524, 0.98787181, 0.40926125],
       [0.1009178 , 0.00876016, 0.6295273 , 0.65225641, 0.42359907],
       [0.22828401, 0.52510119, 0.37122139, 0.97546477, 0.94177005]])

In [0]:
# Crea un arreglo de 3x3 con valores aleatorios
# distribuidos de manera normal con media 0 y desviacion estandard 1
np.random.normal(0, 1, (3, 3))

array([[ 1.47362313,  0.41077572, -0.99837656],
       [ 0.20375577, -0.47180483,  0.23902903],
       [-0.4296892 ,  0.96477233, -0.98770808]])

In [0]:
np.random.normal(2, 3, (5, 3))

array([[ 1.69851476, -0.72641586,  4.23668522],
       [ 0.42448452,  9.64037526, -1.94488369],
       [ 8.77733976,  6.21482081,  0.8885052 ],
       [ 0.39468314,  2.48288905,  6.16185754],
       [ 5.19855396, -1.66762225,  2.45754543]])

In [0]:
# Crea array de 3x3 de numeros enterros aleatorios tomados del intervalo [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 2, 2],
       [3, 8, 9],
       [3, 4, 4]])

In [0]:
np.random.randint(0, 100, (3, 4))

array([[64, 70, 72, 42],
       [61, 68, 22, 75],
       [92, 87, 19, 64]])

In [0]:
# Crea matrix identidad de 3x3 (arreglo cuyas entradas son todas cero excepto las diagonales)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [0]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [0]:
# Crea un array de tres enteros sin valores especificos
# Los valores se toman de lo que exista en esa localizacion de la memoria
np.empty(3)

array([1., 1., 1.])

In [0]:
np.empty(2)

array([1.5e-323, 2.0e-323])

##**Basicos de NumPy: arreglos**

In [0]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [0]:
x1

array([5, 0, 3, 3, 7, 9])

In [0]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [0]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [0]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [0]:
print("dtype:", x3.dtype)

dtype: int64


In [0]:
print("dtype:",x2.dtype )

dtype: int64


In [0]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


##**Indexado de Arrays : Acceso a elementos individuales**

In [0]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x2[1, 2]

8

In [0]:
x1

array([5, 0, 3, 3, 7, 9])

In [0]:
x1[-2]

7

##**Rebanadas de Arrays: Accesa a partes (subarrays)**

In [0]:
x=np.arange(5, 20, 2)
x

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [0]:
x[:5]  # first five elements

array([ 5,  7,  9, 11, 13])

In [0]:
x[5:]

array([15, 17, 19])

In [0]:
x[3:6]

array([11, 13, 15])

In [0]:
x[::2]  # every other element

array([ 5,  9, 13, 17])

In [0]:
x[1::2]  # every other element, starting at index 1

array([ 7, 11, 15, 19])

In [0]:

x[::-1]  # all elements, reversed

array([19, 17, 15, 13, 11,  9,  7,  5])

In [0]:
x[5::-2]  # reversed every other from index 5

array([15, 11,  7])

##**Multi-dimensionales**

In [0]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [0]:
x2[:3, ::2]  # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [0]:
x2[:3, ::3]

array([[3, 4],
       [7, 8],
       [1, 7]])

In [0]:
x2[::2, :3]

array([[3, 5, 2],
       [1, 6, 7]])

In [0]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

##**Accesando renglones y columnas del array**

In [0]:

print(x2[:, 0]) 

[3 7 1]


In [0]:
print(x2[0])

[3 5 2 4]


##**Subarrays son vistas y no copias**

In [0]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x4=np.random.randint(10, size=(4, 3))
x4

array([[5, 9, 3],
       [0, 5, 0],
       [1, 2, 4],
       [2, 0, 3]])

In [0]:
x4[:2, :3]

array([[5, 9, 3],
       [0, 5, 0]])

In [0]:
x4[:3, ::2] 

array([[5, 3],
       [0, 0],
       [1, 4]])

In [0]:
x_sub = x2[:2, :2]
print(x2_sub)